### Environment constants

ARCH ?=
CROSS_COMPILE ?=
export

### general build targets

all:
	$(MAKE) all -e -C libtools
	$(MAKE) all -e -C util_net_downlink

clean:
	$(MAKE) clean -e -C libtools
	$(MAKE) clean -e -C util_net_downlink

### EOF
